name: DeployFrontend

on:
  push:
    branches: [ "Frontend" ]
    
jobs:
  Deploy:
    name: Deploy Frontend to EC2 Backend
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Usa la versión de Node.js que prefieras
          
      # Despliegue del Backend si las pruebas unitarias pasan
      - name: Deploy Frontend to EC2 Instance
        env:
          EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SSH_HOST_FRONT }}
          EC2_USER: ${{ secrets.USER_NAME }}
        run: |
          echo "$EC2_PRIVATE_KEY" > ec2_key && chmod 600 ec2_key
          ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} '
              sudo apt update &&
              sudo apt install npm &&
              cd /home/ubuntu/Parcial &&
              git fetch --all &&
              git switch Frontend &&
              git reset --hard origin/Frontend &&
              git pull origin Frontend &&
              cd /home/ubuntu/Parcial/Frontend/paginaparcial &&
              npm install &&
              npm run build &&
              sudo apt update &&
              sudo apt install apache2 &&
              sudo rm -rf /var/www/html/* &&
              sudo chown -R www-data:www-data /var/www/html/ &&
              sudo chmod -R 755 /var/www/html/ &&
              sudo cp -r /home/ubuntu/Parcial/Frontend/paginaparcial/build/* /var/www/html/ &&
              sudo systemctl restart apache2
          '
