name: Deploy

on:
  push:
    branches: [ "master" ]
    
jobs:
  Deploy:
  
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Despliegue del Frontend
      - name: Deploy Frontend to EC2 Instance
        if: github.ref == 'refs/heads/Frontend'
        env:
          EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SSH_HOST_FRONTEND }}
          EC2_USER: ${{ secrets.USER_NAME }}
          FRONTEND_DIR: /home/ubuntu/Parcial/Frontend/paginaparcial
        run: |
          echo "$EC2_PRIVATE_KEY" > ec2_key && chmod 600 ec2_key
          ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} '
              # Acceder al directorio del frontend
              cd ${FRONTEND_DIR} &&

              # Actualizar el código desde la rama frontend
              git fetch --all &&
              git reset --hard origin/frontend &&
              git pull origin frontend &&

              # Instalar dependencias necesarias
              npm install &&

              # Construir la aplicación
              npm run build &&

              # Eliminar el contenido actual de /var/www/html
              sudo rm -rf /var/www/html/* &&

              # Copiar los archivos de la carpeta build/ de tu aplicación React al directorio de Apache
              sudo cp -r build/* /var/www/html/ &&

              # Asegúrate de que los permisos sean correctos
              sudo chown -R www-data:www-data /var/www/html
          '

      # Despliegue del Backend
      - name: Deploy Backend to EC2 Instance
        if: github.ref == 'refs/heads/Backend'
        env:
          EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SSH_HOST_BACKEND }}
          EC2_USER: ${{ secrets.USER_NAME }}
          APP_DIR: /home/ubuntu/Parcial/Backend
          APP_FILE: Servidor.py
        run: |
          echo "$EC2_PRIVATE_KEY" > ec2_key && chmod 600 ec2_key
          ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} '
              # Acceder al directorio del backend
              cd ${APP_DIR} &&

              # Activar el entorno virtual
              source /home/ubuntu/venv/bin/activate &&

              # Actualizar el código desde la rama backend
              git fetch --all &&
              git reset --hard origin/backend &&
              git pull origin backend &&

              # Instalar dependencias necesarias
              pip install -r requirements.txt &&

              # Detener cualquier proceso que esté usando el puerto 5000
              sudo fuser -k 5000/tcp &&

              # Ejecutar la aplicación Flask
              nohup python ${APP_FILE} > flask_server.log 2>&1 &

              # Comprobar si la consola quedó libre
              tail -n 10 flask_server.log
          '
